dist: jammy

services:
  - docker

env:
  global:
    - NIGHTVISION_TARGET=javaspringvulny-api
    - NIGHTVISION_APP=javaspringvulny-api
    - NIGHTVISION_AUTH=javaspringvulny-api
    - secure: <encrypted-NIGHTVISION_TOKEN>
    - secure: <encrypted-SENDER_EMAIL>
    - secure: <encrypted-SENDER_PASSWORD>
    - secure: <encrypted-RECEIVER_EMAIL>

before_install:
  - echo "$SENDER_EMAIL"
  - echo "$RECEIVER_EMAIL"
  - echo "$SENDER_PASSWORD"
  - echo "$NIGHTVISION_TOKEN"
  - sudo apt-get update
  - sudo apt-get install -y docker-compose python3-pip
  - wget -qO- https://downloads.nightvision.net/binaries/latest/nightvision_latest_linux_amd64.tar.gz | tar -xz
  - sudo mv nightvision /usr/local/bin/
  - pip3 install --user semgrep



script:
  - echo "(3) Extract API documentation from code"
  - |
    nightvision swagger extract ./ -t $NIGHTVISION_TARGET --lang spring || true
    if [ ! -e openapi-spec.yml ]; then
        cp backup-openapi-spec.yml openapi-spec.yml
    fi

  - echo "(4) Start the app"
  - docker-compose up -d
  - sleep 60

  - echo "(5) Scan the API"
  - nightvision scan -t $NIGHTVISION_TARGET -a $NIGHTVISION_APP --auth $NIGHTVISION_AUTH > scan-results.txt
  - nightvision export sarif -s "$(head -n 1 scan-results.txt)" --swagger-file openapi-spec.yml


  - echo "(6) Install nightvision mailer reporter and dependencies"
  - git clone https://github.com/jxbt/nightvision_mail_reporter.git
  - cd nightvision_mail_reporter
  - chmod +x install.sh && sudo ./install.sh
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install -r requirements.txt
  - cd ..

  - echo "(7) Run NightVision mailer reporter"
  - cd nightvision_mail_reporter
  - source .venv/bin/activate
  - python3 main.py --sarif ../results.sarif --sender $SENDER_EMAIL --password "$SENDER_PASSWORD" --receiver $RECEIVER_EMAIL --gmail
