version: "3.2"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
    network_mode: host

  javavulny:
    build: .
    image: stackhawk/javavulny:latest
    container_name: javavulny
    environment:
      SPRING_PROFILES_ACTIVE: postgresql
    network_mode: host
    depends_on:
      - db
