version: "3.2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql

  javavulny:
    build: .
    image: stackhawk/javavulny:latest
    container_name: javavulny
    environment:
      SPRING_PROFILES_ACTIVE: postgresql
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      - db

  nightvisionscanner:
    build:
      context: .
      dockerfile: nightvisionDockerFile
    
    volumes:
      - nightvision:/app/

    depends_on:
      - javavulny


volumes:
  nightvision:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /nightvision
