version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test


jobs:
  test:
    machine:
      image: ubuntu-2204:2024.04.4
      
    environment:
      NIGHTVISION_TARGET: javaspringvulny-api
      NIGHTVISION_APP: javaspringvulny-api
      NIGHTVISION_AUTH: javaspringvulny-api
    steps:
      - checkout

      - run:
          name: Start the app
          command: |
            sudo docker-compose build
            sudo docker-compose up -d
            sleep 20


      - store_artifacts:
          path: /nightnightvision/nightvision-report.pdf
          destination: reports/nightvision-report.pdf

